### ISSUE TITLE
The cell order in the CNV heatmap

### ISSUE THREAD

**Issue by HaotengYan** [broadinstitute/infercnv#164] opened 2019-07-30 13:37 UTC
Hello,

Thank you for development on this wonderful tool! I have two questions which confused me a lot.

1. When plotting the CNV heatmap, is there any methods to cluster the cells only using part of genes, such as all genes in Chr7? I have noticed the parameter "**ref_contig** " in funtion "**plot_cnv**", but I don't understand if it matter and how to set it.

2. How can I plot the heatmap using the order of cells set myself? Is it accessible?

Thanks for your help,
Haoteng Yan

**Comment by GeorgescuC** [comment] 2019-08-05 16:05
Hi @HaotengYan ,

1. For the `ref_contig` option in `plot_cnv`, you can set it to the name of any chromosome as written in the gene coordinates file given as input. However, for it to be taken into account, you will need to remove the clustering information already stored in the infercnv object that is used in priority. To do so, simply set the field to `NULL` in the (copy of the) infercnv_obj like this `infercnv_obj@tumor_subclusters = NULL` then run the plot_cnv method with the desired settings.

2. Right now it is not directly possible. For observations, you could however try to set each cell to a different group name and use the cluster_by_groups=TRUE option (default) so that groups, and hence cells, are ordered as in the expression matrix. This however won't work for references as they need to be in properly defined groups for the analysis to be accurate.
This feature is something I will put on the list of things to add, but it may take a bit of time before I get to it.

Regards,
Christophe.

**Comment by HaotengYan** [comment] 2019-08-27 08:42
Hi @GeorgescuC 

I have plotted cnv heatmap when setting **ref_contig** to "chr1". But it doesn't work when c("chr1", "chr2") are set and here is the error information:

_Error in file(paste(file_base_name, paste(hcl_desc, "HCL", cut_group,  :  
invalid 'description' argument
In addition: Warning message:
In contig_names == cluster_contig :
  longer object length is not a multiple of shorter object length_ 

Yan

**Comment by GeorgescuC** [comment] 2019-08-28 22:07
Hi @HaotengYan ,

Could you please download the latest version of the code on the master branch and reinstall infercnv from it, then retry? This should also allow `plot_cnv()` to recalculate the clustering automatically without you having to delete the `infercnv_obj@tumor_subclusters` field.
[Instructions for installation from github are available on the wiki.](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-by-pulling-the-code-using-git-followed-by-source-installation)

If you still have the same issue with the latest patch, could you please run `options(error = function() traceback(2))` in your R session before running infercnv, and then post the full log?

Regards,
Christophe.

**Comment by HaotengYan** [comment] 2019-08-29 12:17
Hi @GeorgescuC 

Thank you for your reply. I run the following code.

`> infercnv_obj <- readRDS("E:/SingleCell/infercnv/GSE131928/MGH121/preliminary.infercnv_obj")
> options(error = function() traceback(2))
> plot_cnv(infercnv_obj = infercnv_obj, out_dir= "E:/SingleCell/infercnv/test", cluster_by_groups= F, k_obs_groups = 3, ref_contig= c("chr1", "chr2", "chr3"))
INFO [2019-08-29 19:58:42] ::plot_cnv:Start
INFO [2019-08-29 19:58:42] ::plot_cnv:Current data dimensions (r,c)=8333,295 Total=2565894.87329813 Min=0.28337663229205 Max=3.26453795994406.
INFO [2019-08-29 19:58:42] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-08-29 19:58:42] plot_cnv(): auto thresholding at: (0.187343 , 1.900248)
INFO [2019-08-29 19:58:43] plot_cnv_observation:Start
INFO [2019-08-29 19:58:43] Observation data size: Cells= 290 Genes= 8333
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr1
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr2
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr3
INFO [2019-08-29 19:58:43] clustering observations via method: ward.D
INFO [2019-08-29 19:58:43] plot_cnv_observation:Writing observations by grouping.
Error in file(paste(file_base_name, paste(hcl_desc, "HCL", cut_group,  : 
  invalid 'description' argument
In addition: Warning message:
In contig_names == cluster_contig :
  longer object length is not a multiple of shorter object length
4: (function () 
   traceback(2))()
3: file(paste(file_base_name, paste(hcl_desc, "HCL", cut_group, 
       "members.txt", sep = "_"), sep = .Platform$file.sep))
2: .plot_cnv_observations(infercnv_obj = infercnv_obj, obs_data = obs_data, 
       file_base_name = out_dir, do_plot = !is.na(output_format), 
       output_filename_prefix = output_filename, cluster_contig = ref_contig, 
       contigs = contigs, contig_colors = ct.colors[contigs], contig_labels = contig_labels, 
       contig_names = contig_names, col_pal = custom_pal, contig_seps = col_sep, 
       num_obs_groups = k_obs_groups, obs_annotations_groups = obs_annotations_groups, 
       obs_annotations_names = obs_annotations_names, grouping_key_coln = grouping_key_coln[1], 
       cluster_by_groups = cluster_by_groups, cnv_title = title, 
       cnv_obs_title = obs_title, contig_lab_size = contig_cex, 
       breaksList = breaksList_t, x.center = x.center, hclust_method = hclust_method, 
       layout_lmat = force_layout[["lmat"]], layout_lhei = force_layout[["lhei"]], 
       layout_lwid = force_layout[["lwid"]])
1: plot_cnv(infercnv_obj = infercnv_obj, out_dir = "E:/SingleCell/infercnv/test", 
       cluster_by_groups = F, k_obs_groups = 3, ref_contig = c("chr1", 
           "chr2", "chr3"))`

However, the following code is running with no error, which the parameter `ref_contig` seems to be misset to a vector with length more than 1.
`plot_cnv(infercnv_obj = infercnv_obj, out_dir= "E:/SingleCell/infercnv/test", cluster_by_groups= F, k_obs_groups = 3, ref_contig= "chr1")`

Thank you for your help.
Yan

**Comment by HaotengYan** [comment] 2019-08-29 12:25
Thank you for your reply. I run the following code.

`infercnv_obj <- readRDS("E:/SingleCell/infercnv/GSE131928/MGH121/preliminary.infercnv_obj")
plot_cnv(infercnv_obj = infercnv_obj, out_dir= "E:/SingleCell/infercnv/test", cluster_by_groups= F, k_obs_groups = 3, ref_contig= c("chr1", "chr2", "chr3"))
`
The information returned is belows.

`INFO [2019-08-29 19:58:42] ::plot_cnv:Start
INFO [2019-08-29 19:58:42] ::plot_cnv:Current data dimensions (r,c)=8333,295 Total=2565894.87329813 Min=0.28337663229205 Max=3.26453795994406.
INFO [2019-08-29 19:58:42] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-08-29 19:58:42] plot_cnv(): auto thresholding at: (0.187343 , 1.900248)
INFO [2019-08-29 19:58:43] plot_cnv_observation:Start
INFO [2019-08-29 19:58:43] Observation data size: Cells= 290 Genes= 8333
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr1
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr2
INFO [2019-08-29 19:58:43] plot_cnv_observation:Clustering only by contig  chr3
INFO [2019-08-29 19:58:43] clustering observations via method: ward.D
INFO [2019-08-29 19:58:43] plot_cnv_observation:Writing observations by grouping.
Error in file(paste(file_base_name, paste(hcl_desc, "HCL", cut_group,  : 
  invalid 'description' argument
In addition: Warning message:
In contig_names == cluster_contig :
  longer object length is not a multiple of shorter object length
4: (function () 
   traceback(2))()
3: file(paste(file_base_name, paste(hcl_desc, "HCL", cut_group, 
       "members.txt", sep = "_"), sep = .Platform$file.sep))
2: .plot_cnv_observations(infercnv_obj = infercnv_obj, obs_data = obs_data, 
       file_base_name = out_dir, do_plot = !is.na(output_format), 
       output_filename_prefix = output_filename, cluster_contig = ref_contig, 
       contigs = contigs, contig_colors = ct.colors[contigs], contig_labels = contig_labels, 
       contig_names = contig_names, col_pal = custom_pal, contig_seps = col_sep, 
       num_obs_groups = k_obs_groups, obs_annotations_groups = obs_annotations_groups, 
       obs_annotations_names = obs_annotations_names, grouping_key_coln = grouping_key_coln[1], 
       cluster_by_groups = cluster_by_groups, cnv_title = title, 
       cnv_obs_title = obs_title, contig_lab_size = contig_cex, 
       breaksList = breaksList_t, x.center = x.center, hclust_method = hclust_method, 
       layout_lmat = force_layout[["lmat"]], layout_lhei = force_layout[["lhei"]], 
       layout_lwid = force_layout[["lwid"]])
1: plot_cnv(infercnv_obj = infercnv_obj, out_dir = "E:/SingleCell/infercnv/test", 
       cluster_by_groups = F, k_obs_groups = 3, ref_contig = c("chr1", 
           "chr2", "chr3"))`


However, the following code is running with no error, which the parameter ref_contig seems to be misset to a vector with length more than 1.

`plot_cnv(infercnv_obj = infercnv_obj, out_dir= "E:/SingleCell/infercnv/test", cluster_by_groups= F, k_obs_groups = 3, ref_contig= "chr2")
`

Thank you for your help.
Yan

**Comment by GeorgescuC** [comment] 2019-08-29 22:23
Hi @HaotengYan ,

I was having issues reproducing the error because it only seems to occur when cluster_by_group is set to FALSE (with the default being TRUE), but it should be fixed now. You can pull the latest commit, reinstall infercnv and then run the command again.

Regards,
Christophe.

**Closed** 2019-10-21 17:04 UTC
