### ISSUE TITLE
A hierarchical clustering of all non-reference cells. 

### ISSUE THREAD

**Issue by nuan604** [broadinstitute/infercnv#138] opened 2019-04-09 11:29 UTC
This is a very useful tool! Thanks for developing.

I have a question. I want to use the tool to identify the normal cells from single cells by using the infercnv. There are lots of output files.Which file could we use to get the the normal cells ?

If group_by_cluster=FALSE, the dendrogram on the left is a hierarchical clustering of all non-reference cells. The first color column indicates the subdivisions of the dendrogram by cutting it in k_obs_groups groups. But there is an error in command. How to solve this?

![Screen Shot 2019-04-09 at 7 29 11 PM](https://user-images.githubusercontent.com/39118079/55796956-cc295f80-5afd-11e9-8fe7-b775fbc2b680.png)

Thanks!

**Comment by GeorgescuC** [comment] 2019-04-09 21:25
Hi @nuan604 ,

If you want to select the cells that appear to be normal cells based on the dendrogram with group_by_cluster=FALSE and the k_obs_group split, you can use the first two columns from the file `observation_groupings.txt`, which will give you the cell ID and the associated group grouping € [1;k].
I would just recommend being careful when you interpret the results as for example having 10% normal cells and 90% mutant cells with a gain in a given region are more likely to look as if the 10% normal cells have a loss (you can see this happen in our provided example when you run it without defining the references).

For the error you have when running infercnv, did you get any error before that point when running `CreateInfercnvObject` ? It seems like the method does not give a hard error if you do not specify the `ref_group_names` at all, but only later at the point your run did. If you could try giving an empty list as an argument like `ref_group_names=c()`, it should work.

Regards.

**Comment by nuan604** [comment] 2019-04-10 13:33
> Hi @nuan604 ,
> 
> If you want to select the cells that appear to be normal cells based on the dendrogram with group_by_cluster=FALSE and the k_obs_group split, you can use the first two columns from the file `observation_groupings.txt`, which will give you the cell ID and the associated group grouping € [1;k].
> I would just recommend being careful when you interpret the results as for example having 10% normal cells and 90% mutant cells with a gain in a given region are more likely to look as if the 10% normal cells have a loss (you can see this happen in our provided example when you run it without defining the references).
> 
> For the error you have when running infercnv, did you get any error before that point when running `CreateInfercnvObject` ? It seems like the method does not give a hard error if you do not specify the `ref_group_names` at all, but only later at the point your run did. If you could try giving an empty list as an argument like `ref_group_names=c()`, it should work.
> 
> Regards.

Hi @GeorgescuC 

Thanks for your reply. 

I want to identify the normal cells(immune cells) from single cell data of the bulk cancer. So I can not set the ref cells. I test if we can separate the normal cells by infercnv. I use the command group_by_cluster=FALSE and the k_obs_group=2, but the cells do not separate.But the figure we can see the cells are different. How to solve this problem?Thanks!

![infercnv preliminary](https://user-images.githubusercontent.com/39118079/55883029-239bfe00-5bd8-11e9-945e-1882f4299e83.png)

**Comment by GeorgescuC** [comment] 2019-04-10 20:41
Hi @nuan604 ,

I was able to reproduce the problem and figured out where the issue comes from, but I need a bit of time to make a proper fix. Basically some of our newer features (subclustering and the HMM) made it so that group_by_cluster is in practice ignored, so I need to have them take it into account.

I will update you as soon as the fix is ready.

Regards.

**Comment by nuan604** [comment] 2019-04-11 02:24
> Hi @nuan604 ,
> 
> I was able to reproduce the problem and figured out where the issue comes from, but I need a bit of time to make a proper fix. Basically some of our newer features (subclustering and the HMM) made it so that group_by_cluster is in practice ignored, so I need to have them take it into account.
> 
> I will update you as soon as the fix is ready.
> 
> Regards.

Hi @GeorgescuC ,

Thanks so much for your reply.From the figure, I can see the cells are separated. So I trust the subclustering features could be done by infercnv soon. I am looking forward that the fix is ready.
I really appreciate your work.Thanks!


Best.

**Comment by GeorgescuC** [comment] 2019-04-16 20:30
Hi @nuan604 ,

The issue should now be fixed on our devel branch. You can install it using `devtools::install_github("broadinstitute/infercnv", ref="devel")` .

**Comment by nuan604** [comment] 2019-04-18 05:08
> Hi @nuan604 ,
> 
> The issue should now be fixed on our devel branch. You can install it using `devtools::install_github("broadinstitute/infercnv", ref="devel")` .

Hi @GeorgescuC ,

Thanks for updating the tool. But I tried the demo data. There are still some problem. I upload the png for you.  The sub-cluster do not separate the normal from cancer cells well.

Do you think we can improve this?Thanks.
![Uploading infercnv.png…]()

Best,
Ziyi

**Comment by GeorgescuC** [comment] 2019-04-18 14:39
Hi @nuan604 ,

I think there was an issue with uploading your image, the link points to this same thread rather than a file.

Best,
Christophe

**Comment by nuan604** [comment] 2019-04-19 02:24
> Hi @nuan604 ,
> 
> I think there was an issue with uploading your image, the link points to this same thread rather than a file.
> 
> Best,
> Christophe

Hi @GeorgescuC ,

This is the figure

![infercnv](https://user-images.githubusercontent.com/39118079/56401812-45a71780-628d-11e9-8be3-e0b95da43ef7.png)

**Comment by GeorgescuC** [comment] 2019-04-19 03:33
Hi @nuan604 ,

This looks like the data you can load using data(data), which is not
meaningful data but for the only purpose of having a very small dataset
that runs in the documentation example on the automated build systems of
bioconductor in seconds (as the whole build and checks need to run in less
than 5 minutes). As written in the description "Generated SmartSeq2
expression data with 10 normal cells and 10 tumor cells.
This is only to demonstrate how to use methods, not actual data to be used
in an analysis."

If you want a proper example set, you can use the one in the "example"
directory in the github.

Best,
Christophe.

**Comment by nuan604** [comment] 2019-04-24 03:03
> Hi @nuan604 , This looks like the data you can load using data(data), which is not meaningful data but for the only purpose of having a very small dataset that runs in the documentation example on the automated build systems of bioconductor in seconds (as the whole build and checks need to run in less than 5 minutes). As written in the description "Generated SmartSeq2 expression data with 10 normal cells and 10 tumor cells. This is only to demonstrate how to use methods, not actual data to be used in an analysis." If you want a proper example set, you can use the one in the "example" directory in the github. Best, Christophe.
> […](#)

Hi @GeorgescuC ,

Thanks for your reply. I tried the demo data firstly. The image is the result of your demo data. Maybe I need to download the example data.

By the way I want to confirm that the cnv data of each steps were save in the obj file.Are these data saved in the infercnv_obj@ expr.data? I mean the calculated CNV results.Thanks!

Best,
Ziyi

**Comment by GeorgescuC** [comment] 2019-04-24 16:01
Hi @nuan604 ,

The example data is stored in "inst/extdata/", and you can use "example/run.R" to run it (from within the example directory).

The object file saved as an RDS after each step contains the expression matrix at the current step of processing in the @expr.data field yes. If you want a more formatted output, when you run the plot_cnv() method, a set of output files are generated that contain the matrices of references and observations, as well as all the information you can find on the figure (table of cells to group ids, dendrograms). In addition, if you run the HMM, you will get outputs ending in .pred_cnv_genes.dat and .pred_cnv_regions.dat that contain a list of genes/region with the predicted CNV and the start/end positions.

Best,
Christophe.

**Comment by nuan604** [comment] 2019-04-26 07:22
> Hi @nuan604 ,
> 
> The example data is stored in "inst/extdata/", and you can use "example/run.R" to run it (from within the example directory).
> 
> The object file saved as an RDS after each step contains the expression matrix at the current step of processing in the @expr.data field yes. If you want a more formatted output, when you run the plot_cnv() method, a set of output files are generated that contain the matrices of references and observations, as well as all the information you can find on the figure (table of cells to group ids, dendrograms). In addition, if you run the HMM, you will get outputs ending in .pred_cnv_genes.dat and .pred_cnv_regions.dat that contain a list of genes/region with the predicted CNV and the start/end positions.
> 
> Best,
> Christophe.

Hi @GeorgescuC ,

Thanks so much for your reply!

We want to install the infer.cnv on our sever. How to install the infercnv by python(pip)?

Thanks,
Ziyi

**Comment by GeorgescuC** [comment] 2019-04-26 18:27
Hi @nuan604 ,

This is an R package so you will need to run things with R rather than python (although you can call R from within python with a subprocess). It depends on JAGS which can likely be installed directly through the package manager of your server's OS. Alternatively, you can [compile it from source](https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/)

Since the package has now been accepted in BioConductor, the best way to go would be to wait until the 3rd of May when the new BioConductor release (3.9) comes out and install infercnv with:
<pre>
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("infercnv")
</pre>

If you wish to install it sooner, you will need to run 
<pre>
library("devtools")
devtools::install_github("broadinstitute/infercnv")
</pre>
and install any additional dependencies you are missing (see [wiki](https://github.com/broadinstitute/inferCNV/wiki/Installing-infercnv) for more info)

Best,
Christophe.

**Comment by nuan604** [comment] 2019-04-30 04:09
> Hi @nuan604 ,
> 
> This is an R package so you will need to run things with R rather than python (although you can call R from within python with a subprocess). It depends on JAGS which can likely be installed directly through the package manager of your server's OS. Alternatively, you can [compile it from source](https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/)
> 
> Since the package has now been accepted in BioConductor, the best way to go would be to wait until the 3rd of May when the new BioConductor release (3.9) comes out and install infercnv with:
> 
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> BiocManager::install("infercnv")
> If you wish to install it sooner, you will need to run
> 
> library("devtools")
> devtools::install_github("broadinstitute/infercnv")
> and install any additional dependencies you are missing (see [wiki](https://github.com/broadinstitute/inferCNV/wiki/Installing-infercnv) for more info)
> 
> Best,
> Christophe.


Hi @GeorgescuC，

Thanks so much for updating the tool.It is really a nice package.We are looking forward to the version in BioConductor release (3.9).By the way, is this version can do the group_by_cluster=FALSE and the k_obs_group=2?

Your devel branch is really nice! I want to share with you the results we did in some public data.

This figure is from the BRCA_GSE75688.The infercnv can separate the normal cells and cancer cells very well with the annotation.It is so cool.
![infercnv 2](https://user-images.githubusercontent.com/39118079/56940238-ae20af00-6b3f-11e9-816c-134dc8ca9b31.png)

But I also tried to give the annotation about the cancer cells and normal cells. The heatmap changed.The cell are not well cluster as the figure without the annotation .I don't know why.How can I improve this? 
![infercnv k2](https://user-images.githubusercontent.com/39118079/56940388-b2999780-6b40-11e9-87ec-0ee6f318c2b6.png)

Thanks,
Ziyi

**Comment by GeorgescuC** [comment] 2019-04-30 18:41
Hi @nuan604 ,

Yes, the BioConductor release will contain the version of the package with the fixes for cluster_by_group and k_obs_groups.

I see there is indeed an issue with the 2nd plot, but weirdly, the dendrogram on the left of the 2 figures look identical, and it seems like some things get mixed up on the 2nd plot. Have you run both cases in the same output folder? It looks like some results were loaded from the first run to the 2nd (based on the dendrogram), but because the input changed, the cell indexes are different and get mixed. If that is the case, could you try running the 2nd case in a different output folder?

Alternativaly, if that is not the issue, could you give me the list of settings you have used to run this please?

Best,
Christophe.

**Comment by nuan604** [comment] 2019-05-05 03:23
> Hi @nuan604 ,
> 
> Yes, the BioConductor release will contain the version of the package with the fixes for cluster_by_group and k_obs_groups.
> 
> I see there is indeed an issue with the 2nd plot, but weirdly, the dendrogram on the left of the 2 figures look identical, and it seems like some things get mixed up on the 2nd plot. Have you run both cases in the same output folder? It looks like some results were loaded from the first run to the 2nd (based on the dendrogram), but because the input changed, the cell indexes are different and get mixed. If that is the case, could you try running the 2nd case in a different output folder?
> 
> Alternativaly, if that is not the issue, could you give me the list of settings you have used to run this please?
> 
> Best,
> Christophe.

Hi @GeorgescuC ，

Thanks for your reply.  I run it out into different output folder.

This is the command for first figure:
infercnv_obj = CreateInfercnvObject(raw_counts_matrix= "raw_counts_matrix.txt",
                                    annotations_file= "all.cells.txt",
                                    delim="\t",
                                    gene_order_file= "gene_order_file.txt",
                                    ref_group_names=c("normal"))
# perform infercnv operations to reveal cnv signal
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="k2.noanno",  # dir is auto-created for storing outputs
                             cluster_by_groups=F,   # cluster
                             k_obs_groups = 2,
                             denoise=T)

The 2nd figure was generated by this command:

 infercnv_obj = CreateInfercnvObject(raw_counts_matrix= "raw_counts_matrix.txt",
                                    annotations_file= "cell.anno.txt",
                                    delim="\t",
                                    gene_order_file= "gene_order_file.txt",
                                    ref_group_names=c("normal"))
# perform infercnv operations to reveal cnv signal
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="nok.with.anno",  # dir is auto-created for storing outputs
                             cluster_by_groups=T,   # cluster
                             denoise=T)

**Comment by GeorgescuC** [comment] 2019-05-06 21:55
Hi @nuan604 ,

I was able to reproduce a similar issue for that dataset that should now be fixed in devel f7174627a6fc8d4fb6a79c17b1f66a1b6b5c5ae9 (with the version of inputs I generated on my side). The issue was in sorting the cells (and hence the color bars) based on the clustering when cells are not in the same order in the input matrix and the annotation table.

Please let me know if you still have issues.

Best,
Christophe.

**Comment by nuan604** [comment] 2019-05-09 06:49
Hi @GeorgescuC ,

Thanks for solving this problem. Now the infercnv is released in BioConductor.But it is based on the R3.6. In Conda ,the R is still 3.5. Could I install the infercnv in R 3.5?

Thanks,
Ziyi

**Comment by GeorgescuC** [comment] 2019-05-09 15:33
Hi @nuan604 ,

To install on R 3.5, you will need to download the repository and manually edit the `DESCRIPTION` file. You can proceed as following:

```
git clone https://github.com/broadinstitute/infercnv.git
cd infercnv
git checkout devel
sed -i _backup 's/Depends: R(>= 3.6)/Depends: R(>= 3.5)/' DESCRIPTION
R
install.packages("./", repos=NULL, type="source")
```

Best,
Christophe.

**Closed** 2019-10-21 17:35 UTC
