### ISSUE TITLE
infercnv::run samples mode error when ref_group_names = NULL.

### ISSUE THREAD

**Issue by fjrossello** [broadinstitute/infercnv#148] opened 2019-05-20 00:44 UTC
Hi,

I get the following error while running `infercnv::run` (package version 1.0.0) in `samples` mode with an object created using`ref_group_names = NULL`.
 
`STEP 05: Clustering samples (not defining tumor subclusters)`

`INFO [2019-05-19 23:47:30] define_signif_tumor_subclusters(p_val=0.1`

`Error in infercnv_obj@expr.data[, unlist(infercnv_obj@reference_grouped_cell_indices)] :
  invalid or not-yet-implemented 'Matrix' subsetting`

`Calls: <Anonymous> -> define_signif_tumor_subclusters -> [ -> [`

`Execution halted`

Is this expected? It runs OK if `analysis_mode = 'sublclusters'`.

Below the code I used

`inferCNV.NULL.ref <- CreateInfercnvObject(`
  `raw_counts_matrix = GetAssayData(seurat.object, slot = 'counts'),`
  `annotations_file = "cell_ann.txt",`
  `delim = "\t",`
  `gene_order_file = "hg19-3.0.0_gene_pos_dedup.txt",`
  `ref_group_names = NULL,`
  `chr_exclude = NULL`
`)`

`inferCNV.NULL.ref. samples <-`
 ` infercnv::run(`
   `inferCNV.NULL.ref,`
  `cutoff = 0.1,`
`  out_dir = "./samples",`
`   cluster_by_groups = F,`
`   analysis_mode = 'samples',`
`   cluster_references = FALSE,`
`   denoise = T,`
`   HMM = F,`
`   num_threads = 12`
 ` )`

Thanks in advance.

Fernando

**Comment by GeorgescuC** [comment] 2019-05-20 16:44
Hi @fjrossello ,

I was unable to reproduce the error, but from searching about it in other R packages, it would seem the issue is with the type of the matrix for the read counts. Could you try to add an `as.matrix()` call around `GetAssayData()`?

If you could also send me the output from `is(inferCNV.NULL.ref@expr.data)`, I may be able to reproduce the issue.

Regards,
Christophe.

**Comment by fjrossello** [comment] 2019-05-20 23:52
Hi Christophe,

> I was unable to reproduce the error, but from searching about it in other R packages, it would seem the issue is with the type of the matrix for the read counts. 

Yes, that's what I thought. 

> Could you try to add an as.matrix() call around GetAssayData()?

It's a biggish set (~120,000 cells) thus I cannot load it as matrix. 

> If you could also send me the output from is(inferCNV.NULL.ref@expr.data), I may be able to reproduce the issue.

Find it below:
`is(inferCNV.NULL.ref@expr.data)`
` [1] "dgCMatrix"      "CsparseMatrix"  "dsparseMatrix"  "generalMatrix"  "dCsparseMatrix" "AnyMatrix"`  
` [7] "dMatrix"        "sparseMatrix"   "compMatrix"     "Matrix"         "xMatrix"        "mMatrix" `      
`[13] "Mnumeric"       "replValueSp`

By the way, I tried `as.matrix` using a subset of 7,000 cells and I don't get the error, thus I think that this error comes from the fact that I am using a sparse matrix.

Thanks for your prompt reply.

Cheers,

Fernando

**Comment by GeorgescuC** [comment] 2019-05-21 16:52
Hi @fjrossello , 

The issue was indeed due to the sparse matrix. We actually have a script to transform the input to a sparse matrix which we used without any issues before, but that is because we always use a reference. The issue should now be fixed in the RELEASE_3_9 branch (which should update to the live BioConductor version too with the next build for version 1.0.2).
It was working fine with `analysis_mode = 'subclusters'` because that mode uses random trees to define subclusters by default, while the issue only occurred when using the non random trees methods. 

However, based on the size of your matrix, I would strongly recommend using our master branch (that will match the BioConductor devel). Plotting 120k cells will take an extremely long time (appears to be because of how the R "image()" method works) based on our tests with 80k cells, but the master branch has 2 new methods that allow to sample the data you plot `sample_object()`, or to plot each group of cells (based on annotations if using cluster_by_group=TRUE) on a separate figure `plot_per_group()`.
You will want to use the additional option `no_plot=TRUE` in `run()` to disable all full-data plots, then use the 2 methods mentioned above to do the plotting from the final results object. If you have any questions about how to use them, please let me know.

Best,
Christophe.

**Comment by fjrossello** [comment] 2019-05-22 00:22
Hi @GeorgescuC,

Great! Thanks for looking into this so promptly. I will do as suggested.

Kind regards,

Fernando

**Closed** 2019-05-22 00:23 UTC
