### ISSUE TITLE
Error in CreateInfercnvObject function

### ISSUE THREAD

**Issue by chatterjee89** [broadinstitute/infercnv#332] opened 2021-06-02 19:50 UTC
Hi,
Thank you for developing the package!
I'm getting the following error:

```
> infercnv_obj = CreateInfercnvObject(raw_counts_matrix=GetAssayData(seurat_obj, slot="counts"),
+                                     annotations_file=ca,
+                                     delim="\t",
+                                     gene_order_file="/home/inferCNV_input/your_gen_pos.txt",
+                                     ref_group_names = c("CTRL_FC"))
INFO [2021-06-02 14:46:40] Parsing gene order file: /home/inferCNV_input/your_gen_pos.txt
INFO [2021-06-02 14:46:40] ::order_reduce:Start.
INFO [2021-06-02 14:46:40] .order_reduce(): expr and order match.
INFO [2021-06-02 14:46:40] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 13948,32412 Total=91889163 Min=0 Max=853.
INFO [2021-06-02 14:46:40] num genes removed taking into account provided gene ordering list: 1071 = 7.67852021795239% removed.
INFO [2021-06-02 14:46:41] validating infercnv_obj
Warning messages:
1: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  number of items read is not a multiple of the number of columns

```
I have run this command with other set of data sometime last year and it worked.
The input files seem to be in order. What am I doing wrong?

**Comment by ash262** [comment] 2021-06-24 10:44
I have the same issue! Look forward to your help! 

My code is like chatterjee89's, with this error message:

...
INFO [2021-06-02 14:46:41] validating infercnv_obj
Warning messages:
1: In for (j in 1:len) { :
  closing unused connection 4 (//.../4_raw_counts.txt.gz)
2: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  number of items read is not a multiple of the number of columns

**Comment by GeorgescuC** [comment] 2021-06-25 03:38
Hi @chatterjee89 ,

Are there any single quotes `'` in one of your input files? If yes try removing/replacing them and creating the infercnv object again.

To help identify in which file the issue is, you can run these 2 lines that are used to read the file inputs and see which one is the culprit:
```
gene_order <- read.table(gene_order_file, header=FALSE, row.names=1, sep="\t", check.names=FALSE)
input_classifications <- read.table(annotations_file, header=FALSE, row.names=1, sep=delim, stringsAsFactors=FALSE, colClasses = c('character', 'character'))
```

Regards,
Christophe.

**Comment by GeorgescuC** [comment] 2021-06-25 03:38
Hi @ash262 ,

The error you have seems to be slightly different, can you please let me know what command you run exactly?

Regards,
Christophe.

**Closed** 2022-03-04 18:20 UTC
