### ISSUE TITLE
An error that occurred at Step 18.

### ISSUE THREAD

**Issue by Rui-Jing** [broadinstitute/infercnv#377] opened 2021-11-16 08:46 UTC
Hi,
Recently , I used Infercnv to process my single-cell data. In the STEP 18, an error occurred.

**Error is:**
	STEP 18: Run Bayesian Network Model on HMM predicted CNV's

INFO [2021-11-16 05:01:28] Creating the following Directory:  /home/pc/infercnv//BayesNetOutput.HMMi6.rand_trees.hmm_mode-subclusters
INFO [2021-11-16 05:01:28] Initializing new MCM InferCNV Object.
INFO [2021-11-16 05:01:28] validating infercnv_obj
**Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “character” is not valid for @‘cnv_regions’ in an object of class “MCMC_inferCNV”; is(value, "factor") is not TRUE**

My code

> infercnv_obj = CreateInfercnvObject(
  raw_counts_matrix=counts_p121_2,
  annotations_file="/home/pc/p121_2_annotation.txt",
  delim="\t",
  gene_order_file="/home/zfzf/mm_geneOrderingFile.txt",
  ref_group_names=c("P121_2_Oligodendrocytes","P121_2_Macrophages","P121_2_Microglia-1",
                    "P121_2_Proliferation-related immune cells","P121_2_Microglia-2","P121_2_Ependymal cells"))

> infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir="/home/pc/infercnv/",
                             cluster_by_groups=FALSE, 
                             analysis_mode="subclusters", 
                             denoise=TRUE,
                             HMM=TRUE,
                             HMM_type = "i6",
                             num_threads=4)

My infercnv version is **1.3.3**
I sincerely hope to get your kind help.

**Comment by GeorgescuC** [comment] 2021-11-19 03:39
Hi @Rui-Jing ,

Version 1.3.3 is very outdated at this point, and it's likely the issue is fixed in the current version of infercnv. After an update, you may want to delete the current output folder for the reload not to mistakenly reload the old object that will probably produce errors.

Regards,
Christophe.

**Closed** 2022-03-04 18:20 UTC

**Comment by Yieryoyo** [comment] 2023-08-02 16:05
> Hi @Rui-Jing ,
> 
> Version 1.3.3 is very outdated at this point, and it's likely the issue is fixed in the current version of infercnv. After an update, you may want to delete the current output folder for the reload not to mistakenly reload the old object that will probably produce errors.
> 
> Regards, Christophe.

Hi~ @GeorgescuC 
I downloaded version 1.3.3 infercnv installation package  from the website **https://github.com/broadinstitute/infercnv/releases**, which showed the date of update is Feb 8, 2020. However, I still met the same problem at run time, is this the latest version?
