### ISSUE TITLE
Error in base::rowMeans

### ISSUE THREAD

**Issue by s2hui** [broadinstitute/infercnv#156] opened 2019-06-20 00:36 UTC
I ran the following to create the infercnv object (I don't have any reference cells so I set ref_group_names = NULL as suggested by the wiki):

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=paste0(ROOTDIR,"/out/inferCNV/",NAME,".counts.matrix"),
                                  annotations_file=paste0(ROOTDIR,"/out/inferCNV/",NAME,".annotations.txt"),
                                    delim="\t",
                                    gene_order_file=paste0(ROOTDIR,"/out/inferCNV/chr12p12-ordering.txt"),
                                    ref_group_names=NULL)

This completed successfully, but when I run the next command:
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir=paste0(ROOTDIR,"/out/inferCNV/out"),  # dir is auto-created for storing outputs
                             cluster_by_groups=F,   # cluster
                             denoise=T,
                             HMM=T)

I get the following error:

INFO [2019-06-19 20:26:46] ::process_data:Start
INFO [2019-06-19 20:26:46] 

	STEP 1: incoming data

INFO [2019-06-19 20:26:46] 

	STEP 02: Removing lowly expressed genes

INFO [2019-06-19 20:26:46] -restoring infercnv_obj from /inferCNV/out/02_reduced_by_cutoff.infercnv_obj
INFO [2019-06-19 20:26:46] 

	STEP 03: normalization by sequencing depth

INFO [2019-06-19 20:26:46] normalizing counts matrix by depth
INFO [2019-06-19 20:26:46] Computed total sum normalization factor as median libsize: 0.000000
INFO [2019-06-19 20:26:46] Adding h-spike
INFO [2019-06-19 20:26:46] -no normals defined, using all observation cells as proxy
INFO [2019-06-19 20:26:46] -hspike modeling of normalsToUse
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

I am not sure what this error means or how to fix it.  I would appreciate your insight.  Thanks very much,
shui

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] infercnv_1.0.2              usethis_1.5.0               devtools_2.0.2             
 [4] GSEABase_1.46.0             graph_1.62.0                annotate_1.62.0            
 [7] XML_3.98-1.20               AnnotationDbi_1.46.0        GSVA_1.32.0                
[10] cowplot_0.9.4               scClustViz_1.1.7            shiny_1.3.2                
[13] ggplot2_3.2.0               future_1.13.0               dplyr_0.8.1                
[16] Seurat_3.0.1                SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.0
[19] DelayedArray_0.10.0         BiocParallel_1.18.0         matrixStats_0.54.0         
[22] Biobase_2.44.0              GenomicRanges_1.36.0        GenomeInfoDb_1.20.0        
[25] IRanges_2.18.1              S4Vectors_0.22.0            BiocGenerics_0.30.0        

loaded via a namespace (and not attached):
  [1] utf8_1.1.4             reticulate_1.12        R.utils_2.8.0          tidyselect_0.2.5      
  [5] RSQLite_2.1.1          htmlwidgets_1.3        grid_3.6.0             Rtsne_0.15            
  [9] munsell_0.5.0          codetools_0.2-16       ica_1.0-2              withr_2.1.2           
 [13] argparse_2.0.1         colorspace_1.4-1       rstudioapi_0.10        ROCR_1.0-7            
 [17] gbRd_0.4-11            listenv_0.7.0          Rdpack_0.11-0          labeling_0.3          
 [21] GenomeInfoDbData_1.2.1 bit64_0.9-7            rprojroot_1.3-2        coda_0.19-2           
 [25] vctrs_0.1.0            TH.data_1.0-10         lambda.r_1.2.3         fastcluster_1.1.25    
 [29] R6_2.4.0               markdown_1.0           doParallel_1.0.14      rsvd_1.0.1            
 [33] locfit_1.5-9.1         reshape_0.8.8          bitops_1.0-6           assertthat_0.2.1      
 [37] promises_1.0.1         SDMTools_1.1-221.1     scales_1.0.0           multcomp_1.4-10       
 [41] gtable_0.3.0           npsurv_0.4-0           globals_0.12.4         processx_3.3.1        
 [45] sandwich_2.5-1         rlang_0.3.4            zeallot_0.1.0          splines_3.6.0         
 [49] lazyeval_0.2.2         rjags_4-8              reshape2_1.4.3         backports_1.1.4       
 [53] httpuv_1.5.1           tools_3.6.0            gplots_3.0.1.1         RColorBrewer_1.1-2    
 [57] sessioninfo_1.1.1      ggridges_0.5.1         Rcpp_1.0.1             plyr_1.8.4            
 [61] zlibbioc_1.30.0        purrr_0.3.2            RCurl_1.95-4.12        ps_1.3.0              
 [65] prettyunits_1.0.2      pbapply_1.4-0          viridis_0.5.1          zoo_1.8-6             
 [69] ggrepel_0.8.1          cluster_2.0.8          fs_1.3.1               magrittr_1.5          
 [73] data.table_1.12.2      futile.options_1.0.1   lmtest_0.9-37          RANN_2.6.1            
 [77] mvtnorm_1.0-11         fitdistrplus_1.0-14    pkgload_1.0.2          lsei_1.2-0            
 [81] mime_0.7               xtable_1.8-4           gridExtra_2.3          compiler_3.6.0        
 [85] tibble_2.1.3           KernSmooth_2.23-15     crayon_1.3.4           R.oo_1.22.0           
 [89] htmltools_0.3.6        later_0.8.0            tidyr_0.8.3            geneplotter_1.62.0    
 [93] libcoin_1.0-4          DBI_1.0.0              formatR_1.7            MASS_7.3-51.4         
 [97] Matrix_1.2-17          cli_1.1.0              R.methodsS3_1.7.1      gdata_2.18.0          
[101] metap_1.1              igraph_1.2.4.1         pkgconfig_2.0.2        coin_1.3-0            
[105] plotly_4.9.0           foreach_1.4.4          XVector_0.24.0         bibtex_0.4.2          
[109] stringr_1.4.0          callr_3.2.0            digest_0.6.19          findpython_1.0.5      
[113] sctransform_0.2.0      tsne_0.1-3             edgeR_3.26.4           curl_3.3              
[117] gtools_3.8.1           modeltools_0.2-22      nlme_3.1-139           jsonlite_1.6          
[121] futile.logger_1.4.3    limma_3.40.2           desc_1.2.0             viridisLite_0.3.0     
[125] fansi_0.4.0            pillar_1.4.1           lattice_0.20-38        httr_1.4.0            
[129] pkgbuild_1.0.3         survival_2.44-1.1      glue_1.3.1             remotes_2.0.4         
[133] png_0.1-7              shinythemes_1.1.2      iterators_1.0.10       bit_1.1-14            
[137] stringi_1.4.3          blob_1.1.1             caTools_1.17.1.2       memoise_1.1.0         
[141] irlba_2.3.3            future.apply_1.2.0     ape_5.3

**Comment by GeorgescuC** [comment] 2019-06-20 15:21
Hi @s2hui ,

There appears to be an issue in reading the input data seeing the log "INFO [2019-06-19 20:26:46] Computed total sum normalization factor as median libsize: 0.000000". I also see that for step 2, results from a previous run attempt were loaded, overwriting potential fixes you made to the input.
Could you add the "resume_mode=FALSE" option to infercnv::run() to disable loading of previous results and see if the issue persists? If it does, I will need more details about the input files format.

Regards,
Christophe.

**Comment by s2hui** [comment] 2019-06-20 15:44
Thanks for your reply, I now get the following error:

....
INFO [2019-06-20 11:43:46] Adding h-spike
INFO [2019-06-20 11:43:46] -no normals defined, using all observation cells as proxy
INFO [2019-06-20 11:43:46] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed

Please let me know if I can supply more details re: input files etc...
shui

**Comment by GeorgescuC** [comment] 2019-06-20 16:07
Hi @s2hui , 

If you are willing to share the input files, that should be the easiest to figure out the issue(s) as they seem to be related to reading the data. I will keep the data private obviously. You can send them to cgeorges at broadinstitute dot org.

Otherwise you will need to inspect the objected created from CreateInfercnvObject(), mainly the @count.data and @expr.data fields and see what is different from the input files.

Regards,
Christophe.

**Comment by s2hui** [comment] 2019-06-21 11:38
Hello,
The gene ordering file I used only contained genes from chr12 and this doesn't seem like an adequate number of genes for the software to run properly?  Is this right?
Because when I use the genes from across all chromosomes as in gencode_v21_genes.complete.txt it seems to work (or at least I do not see any errors as before).  I am new to this software so apologies if I have misunderstood anything.
Thanks for your insight. 
shui

**Comment by mea2712** [comment] 2019-08-05 14:48
Hi!
Im running inferCNV on a number of samples ( a different run for each sample) and for 2 of them I get an error always in step 3:

INFO [2019-08-05 15:40:06] Computed total sum normalization factor as median libsize: 22621.000000
INFO [2019-08-05 15:40:06] Adding h-spike
INFO [2019-08-05 15:40:06] -hspike modeling of normal_immune
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) :
  'x' must be an array of at least two dimensions
Calls: <Anonymous> ... .get_mean_var_given_matrix -> rowMeans -> rowMeans -> <Anonymous>
Execution halted

And

INFO [2019-08-05 15:44:48] Computed total sum normalization factor as median libsize: 18747.000000
INFO [2019-08-05 15:44:48] Adding h-spike
INFO [2019-08-05 15:44:48] -hspike modeling of normal_immune
Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df,  :
  singular gradient
Calls: <Anonymous> ... .get_simulated_cell_matrix_using_meanvar_trend -> .get_logistic_params -> nls
Execution halted

Could you point me to where I should start troubleshooting?
Thank you!!

**Comment by GeorgescuC** [comment] 2019-08-05 18:00
Hi @s2hui ,

If you are only providing chr12 genes, there may not be enough data to properly model the distribution of the expression values, but without having your data I cannot say for sure.

Regards,
Christophe

**Comment by GeorgescuC** [comment] 2019-08-05 18:00
Hi @mea2712 ,

For the first error, does your "normal_immune" set contain at least 2 cells?

For both, could you please send the full run log? There are often issues with reading/filtering the data that lead to errors in this step.

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-08-06 08:48
Hi @GeorgescuC ,
For the first error my normal_immune set consists of 8 cells. My tumor cells consist of 6 sets ranging from 177 to 1 cells.
For the second error my normal_immune set consists of 6 cells.My tumor ccells consist of 5 sets ranging from 168 to 3 cells.
Attached are the 2 logs.
Thanks!!!
[logs.zip](https://github.com/broadinstitute/infercnv/files/3471198/logs.zip)

**Comment by GeorgescuC** [comment] 2019-08-06 17:59
Hi @mea2712 ,

For the first dataset, the error occurs because of the tumor set with only 1 cell, for the second, I think the issue has to do with there not being enough cells in the 3 cells set for the model to be properly identified.
Overall, to work properly and be accurate, infercnv requires at least 10-20 cells in a set because of the sparsity of single cell data, especially for 10X which you seem to be using. Depending on how you split your cells, I would recommend either merging them into another similar set, or remove them.

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-08-08 13:03
Hi @GeorgescuC 
I re run my two samples again, this time without the sets containing few cells. That is, one sample contained a normal set of 8 cells and 4 tumor sets with 177, 84, 37, and 15 cells. The other sample contained the normal set with 6 cells and 4 tumor sets with 130,168,21, and 24 cells. This is smartSeq data.
I keep getting similar errors. Should I assume this is because the normal set is too small? Is there anything else I can do?
Thank you!
Attached are the logs
[logs.zip](https://github.com/broadinstitute/infercnv/files/3481833/logs.zip)

**Comment by mea2712** [comment] 2019-08-09 15:21
Hi @GeorgescuC 
I got back the infercnv results from some of my data and I noticed its picking the telomeres as significant CNV. Do you think this has to do with the window size of 101 genes? Thanks!

**Comment by GeorgescuC** [comment] 2019-08-09 16:22
Hi @mea2712 ,

Telomeres should not be part of the inferCNV analysis at all as they do not contain transcribed genes. CNV signal found at the end of chromosomes are only the expressed (so not filtered out) genes that are closest to the start/end of a given chromosome.
About the window size, it will indeed have some effect on the extremities of chromosomes, as only half of the window is available for the first/last gene.

For the issue you have running on those two samples, could you share the data privately so I can try to reproduce the issue and see why it happens?

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-08-12 08:20
Hi @GeorgescuC 
Unfortunately they tell me I cannot share the data. I could try to reproduce the error myself, any tips on where to look?
Thanks!

**Comment by GeorgescuC** [comment] 2019-08-12 19:00
Hi @mea2712 ,

What version of infercnv are you currently using? Based on where the error occurs, it actually seems you are using an older version, as the current one should try to fit a spline when the nls fails .

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-08-21 10:25
Hi @GeorgescuC,
I was running v0.99.4 and have now switched to v1.1.2 from bioconductor.
I re-run all of my samples and everything run smoothly, no errors. Thanks!
However, I noticed in the new results that the CNVs coming out of the Bayes analysis are not in the output of the HMM fitting. I am specifically looking at files: 
1) HMM_CNV_predictions*.pred_cnv_regions.dat
2) */BayesNetOutput/CNV_State_Probabilities.dat
3) HMM_CNV_predictions*.pred_cnv_genes.dat
Why is it that CNVs in 2) are not in 1) ? Is this normal behaviour? I would expect them to be a subset of 1)
Where are CNVs in 2) coming from ?
Thank you!

**Comment by GeorgescuC** [comment] 2019-08-21 18:55
Hi @mea2712 ,

If you are comparing based on region names, the number at end of their name gets reassigned in the Bayesian outputs. The IDs you find in 2) are the IDs of regions defined in 17_HMM_preds.*.dat, while the IDs you find in 1) and 3) are those reassigned at step 18 after the filtering. It is indeed a bit confusing, and I actually noticed this while working on a recent update, so we may change it so that the IDs are preserved.

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-09-09 13:02
Hi @GeorgescuC 
Because the CNVs have different names before and after Bayes fitting, I'm matching the CNVs based on c("cell_group_name","chr","start","end"). And in most cases I get that:
1) the Number of cnvs in HMM_CNV_predictions*.pred_cnv_regions.dat is less than the Number of final significant cnvs after bayesian filtering: /BayesNetOutput/CNV_State_Probabilities.dat
2) A number of CNVs (ranging from 1 to 43)  in HMM_CNV_predictions*.pred_cnv_regions.dat were not found in 17_HMM_preds.pred_cnv_regions.dat 
Could you explain that to me?
Please see attached. Thanks!!

[286_v1.1.2_0.1_0_101.txt](https://github.com/broadinstitute/infercnv/files/3590585/286_v1.1.2_0.1_0_101.txt)

**Comment by GeorgescuC** [comment] 2019-10-21 17:10
Hi @mea2712 ,

Version 1.0.4 changed the way post Bayesian filtering CNVs are named to preserve the names from before filtering. Do you still have the same issue with it?

Regards,
Christophe.

**Comment by mea2712** [comment] 2019-10-23 06:59
Hi @GeorgescuC,
I was using v1.1.2 and had the issue. I ended up using the 17_HMM files though as a work around

**Comment by GeorgescuC** [comment] 2019-10-24 16:30
Hi @mea2712 ,

If you are using the github master/bioconductor devel 1.1.X versions, then the one that has the fix for CNVs IDs post Bayesian filtering is version 1.1.3.

Regards,
Christophe.

**Closed** 2019-11-15 20:57 UTC

**Comment by AForsthuber** [comment] 2021-03-02 08:28
I want to use several subclusters as ref_group_names, namely 7 different, in total 1835. However then I always get this Error message:
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline

The number of cells in the reference group are: 
Endothelial cells: 94     
Fibroblasts: 780     
Immune cells: 395    
Keratinocytes: 249      
Melanocytes: 170
Pericytes_vSMCs: 147
And I compare these to my non-healthy sample (2989 cells).

I tried once without subgrouping my reference sample, just healthy against non-healthy, which did not show this error. However I wonder that the cell numbers per subgroup are too small.

I initially though from what I read in wiki and publications using inferCNV that subgrouping of my reference sample would refine my CNV detection.
However would you recommend now, it the spline instead if singluar gradient accurate enough or should I rather not partition my reference into subgroups?

Thanks in advance !!!


R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
infercnv_1.4.0


infercnv_All.object = CreateInfercnvObject(
  raw_counts_matrix=All.matrix,
  annotations_file=all.af,
  delim="\t",
  gene_order_file=paste0(path, "gencode_v19_gene_pos.txt"),
  ref_group_names=c( "Fibroblasts",
                     "Immune cells",
                     "Melanocytes",
                     "Pericytes_vSMCs",
                     "Endothelial cells",
                     "Immune cells",
                     "Keratinocytes"))

infercnv_obj = infercnv::run(infercnv_All.object,
                             min_cells_per_gene=3,
                             cutoff=1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir=paste0(path,"inferCNV_All"), 
                             cluster_by_groups=T,   # cluster
                             denoise=T,
                             HMM=T,
                             analysis_mode='subclusters',
                             hclust_method='ward.D2',
                             tumor_subcluster_partition_method='random_trees'
)

INFO [2021-03-02 08:42:54] Parsing gene order file: /Users/Agnes/Documents/Schweden/R_projects/gencode_v19_gene_pos.txt
INFO [2021-03-02 08:42:58] ::order_reduce:Start.
INFO [2021-03-02 08:43:00] .order_reduce(): expr and order match.
INFO [2021-03-02 08:43:02] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 26202,4824 Total=2373025206 Min=0 Max=295284.
INFO [2021-03-02 08:43:03] num genes removed taking into account provided gene ordering list: 4623 = 17.6436913212732% removed.
INFO [2021-03-02 08:43:11] validating infercnv_obj

> ############### RUN CNV #########################

INFO [2021-03-02 08:43:14] ::process_data:Start
INFO [2021-03-02 08:43:14] Creating output path /Users/Agnes/Documents/Schweden/R_projects/inferCNV_All_noRefCelltype
INFO [2021-03-02 08:43:14] Checking for saved results.
INFO [2021-03-02 08:43:14] 

	STEP 1: incoming data

INFO [2021-03-02 08:43:53] 

	STEP 02: Removing lowly expressed genes

INFO [2021-03-02 08:43:53] ::above_min_mean_expr_cutoff:Start
INFO [2021-03-02 08:43:53] Removing 5222 genes from matrix as below mean expr threshold: 1
INFO [2021-03-02 08:43:55] validating infercnv_obj
INFO [2021-03-02 08:43:55] There are 16357 genes and 4824 cells remaining in the expr matrix.
INFO [2021-03-02 08:44:03] Removed 16 genes having fewer than 3 min cells per gene = 0.0978174 % genes removed here
INFO [2021-03-02 08:44:05] validating infercnv_obj
INFO [2021-03-02 08:44:40] 

STEP 03: normalization by sequencing depth

INFO [2021-03-02 08:44:40] normalizing counts matrix by depth
INFO [2021-03-02 08:44:44] Computed total sum normalization factor as median libsize: 460819.000000
INFO [2021-03-02 08:44:45] Adding h-spike
INFO [2021-03-02 08:44:45] -hspike modeling of Fibroblasts
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 08:48:33] -hspike modeling of Immune cells
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 08:52:11] -hspike modeling of Melanocytes
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 08:55:50] -hspike modeling of Pericytes_vSMCs
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 08:59:41] -hspike modeling of Endothelial cells
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 09:03:39] -hspike modeling of Keratinocytes
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
INFO [2021-03-02 09:07:27] validating infercnv_obj
INFO [2021-03-02 09:07:27] normalizing counts matrix by depth
INFO [2021-03-02 09:07:28] Using specified normalization factor: 460819.000000
INFO [2021-03-02 09:08:06] 

	STEP 04: log transformation of data

INFO [2021-03-02 09:08:06] transforming log2xplus1()
INFO [2021-03-02 09:08:09] -mirroring for hspike
INFO [2021-03-02 09:08:09] transforming log2xplus1()
INFO [2021-03-02 09:08:48] 
.
.
.
