### ISSUE TITLE
Error in transferring CNV to seurat object with add_to_seurat

### ISSUE THREAD

**Issue by pbrazda** [broadinstitute/infercnv#199] opened 2019-12-04 12:11 UTC
Hi, 

I created an infercnv object by

```
infercnv_TH = infercnv::run(infercnv_TH,
                            cutoff=0.1, 
                            out_dir="output_TH", 
                            cluster_by_groups=TRUE,
                            plot_steps=FALSE,
                            denoise=TRUE, 
                            no_prelim_plot=TRUE,
                            HMM=TRUE) 
```
All fine, got the graphs.
Now I'm trying to transfer the CNV metadata to the seurat object:
```
seu_TH = infercnv::add_to_seurat(infercnv_output_path="~/output_TH",
                                      seurat_obj=seu_TH)
```
but I run into:
```
Error in if (infercnv_obj@options$HMM_report_by == "cell") { : 
  argument is of length zero
```
If I look into the created infercnv object, @options$HMM_report_by is indeed not there, only @options$HMM.

Any tips?

Thank you!

Peter

**Comment by GeorgescuC** [comment] 2019-12-06 21:40
Hi @pbrazda ,

This issue was fixed on master, but no new version was released with the fix yet. It is now available in both version 1.2.2 (BioConductor 3.10, github branch RELEASE_3_10) and 1.3.2 (BioConductor devel, github branch master).

You can either update right away by pulling the code from github and installing (you can use the method shown [on the wiki](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-c-install-infercnv-from-within-r-using-devtools) by setting the ref to "master" or "RELEASE_3_10"), or you can wait for the new BioConductor 3.10/devel build to be ready in a day or two and update through BioConductor.

Regards,
Christophe.

**Comment by pbrazda** [comment] 2019-12-07 14:16
**Thank you for the tip!**
I gave it another run.
The run was:
```
infercnv_H3T = infercnv::run(infercnv_H3T,
                             cutoff=0.1, 
                             out_dir="output_H3T_HMM", 
                             cluster_by_groups=T,
                             plot_steps=F,
                             denoise=T, 
                             no_prelim_plot=T,
                             HMM=T) 
```

It ended up in this message at **STEP 18: Run Bayesian Network Model on HMM predicted CNV's**
	

```
INFO [2019-12-07 13:29:10] Creating the following Directory:  output_H3T_HMM/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2019-12-07 13:29:10] Initializing new MCM InferCNV Object.
INFO [2019-12-07 13:29:10] validating infercnv_obj
INFO [2019-12-07 13:29:10] Total CNV's:  75
INFO [2019-12-07 13:29:10] Loading BUGS Model.
INFO [2019-12-07 13:29:11] Running Sampling Using Parallel with  4 Cores
INFO [2019-12-07 14:40:31] Obtaining probabilities post-sampling
Error in do.call(rbind, mcmc[[j]]) : second argument must be a list
In addition: Warning message:
In parallel::mclapply(seq_along(obj@cell_gene), FUN = par_func,  :
  scheduled cores 1, 2, 3, 4 did not deliver results, all values of the jobs will be affected
```

is it a CPU problem at my side or you think it's in the script?

P

**Comment by GeorgescuC** [comment] 2019-12-09 20:47
Hi @pbrazda ,

We have seen this error from a couple different people, and it seems to be related to the memory available (increasing with the number of threads). Can you maybe increase the memory available to the job, or try to reduce the number of threads?

Regards,
Christophe.

**Closed** 2019-12-10 08:11 UTC

**Comment by shankara-a** [comment] 2020-02-21 15:43
Hello! I wanted to follow up on this. I see the issue is closed but does not seem like there is an explicit suggestion as to what worked.

> We have seen this error from a couple different people, and it seems to be related to the memory available (increasing with the number of threads). Can you maybe increase the memory available to the job, or try to reduce the number of threads?

I am currently running this on an 8 core, 52 gb google cloud VM using your latest docker image and ran into the same error. Did anyone ever solve why this error comes up:

```
        STEP 18: Run Bayesian Network Model on HMM predicted CNV's

INFO [2020-02-21 08:10:07] Creating the following Directory:  ./output//BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2020-02-21 08:10:07] Initializing new MCM InferCNV Object.
INFO [2020-02-21 08:10:07] validating infercnv_obj
INFO [2020-02-21 08:10:07] Total CNV's:  500
INFO [2020-02-21 08:10:07] Loading BUGS Model.
INFO [2020-02-21 08:10:10] Running Sampling Using Parallel with  4 Cores
INFO [2020-02-21 14:34:58] Obtaining probabilities post-sampling
Error in do.call(rbind, mcmc[[j]]) : second argument must be a list
Calls: <Anonymous> ... runMCMC -> getProbabilities -> getProbabilities -> do.call
In addition: Warning message:
In parallel::mclapply(seq_along(obj@cell_gene), FUN = par_func,  :
  scheduled cores 3, 4 did not deliver results, all values of the jobs will be affected
Execution halted
root@d3340c42ea34:/home#```

**Comment by GeorgescuC** [comment] 2020-02-21 17:00
Hi @shankara-a ,

The issue seems to be related to how rjags/jags handle memory when using multiple threads, which is not transparent and makes it hard to pinpoint.  What solved the issue for most people I heard back from was reducing the number of threads (memory probably needs a bigger increase before it is enough).
How many cells do you have in your dataset?

Regards,
Christophe.

**Comment by shankara-a** [comment] 2020-02-21 17:07
Hi @GeorgescuC - thanks for the quick response.

Roughly 30K cells. 

I am monitoring memory right now and actually **increased** threads to 16 along with my memory to ~102 GB on my VM. Not sure how decreasing threads would fix a memory issue unless rjags does not scale linearly memory with cpu usage?

I also explicitly defined R's memory limit with: `memory.limit(size=102400)`. It's currently running right now so hopefully it'll either pass STEP 18 or fail in the next hour?

**Comment by GeorgescuC** [comment] 2020-02-21 18:01
Hi @shankara-a ,

When trying to track memory usage depending on the number of threads for step 18, it did not seem to vary, but that this error does occur and can be solved by reducing threads or increasing memory hints that there still is a difference. I would usually expect some overhead per core to happen as not everything can be shared memory, so there may be some untracked memory with jags.

In your case, even when running on a VM with 8 cores, infercnv was only set to use 4 threads based on the log, so I don't think increasing the number of VM cores to 16 will change anything, unless that is a requirement to increase the RAM available.

Another thing worth mentioning for your run is that you can check the preliminary plot and see if your samples seem to have different subclones within them. If that is the case, you may want to run infercnv with the subclustering analysis mode as explained [here](https://github.com/broadinstitute/infercnv/wiki/infercnv-tumor-subclusters)

Regards,
Christophe.

**Comment by shankara-a** [comment] 2020-02-21 18:10
Hi @GeorgescuC 

Ah yes I caught the `num_threads` argument and changed that to 16 before re-trying STEP 18.

Thank you for sharing your experience with this! I will try the sub-clustering analysis and check the plots - thank you for the tip.

**Comment by shankara-a** [comment] 2020-02-21 19:52
@GeorgescuC 

Just to update - it got past STEP 18 with 16 cores. I think setting the `memory.limit(size=102400)` helped. It took roughly 3 hours.

Thanks so much for your help!

**Comment by Zymaniswenzai** [comment] 2021-05-20 00:59
@shankara-a 
Hi, I have same problem. After reading the above content carefully, I'm wondering how to re-run STEP 18.
Thanks for your help!
