### ISSUE TITLE
add_to_seurat doesn't return updated metadata with analysis_mode='subclusters'

### ISSUE THREAD

**Issue by blakecaldwell** [broadinstitute/infercnv#353] opened 2021-08-18 16:23 UTC
Hello, this is something I noticed that might be a potential bug. I was able to workaround it with this [code change](https://github.com/blakecaldwell/infercnv/commit/05a840e32e18394390035af0afcc0547909ef38d). However, I'm creating this issue to see if there's a better fix for master.

I noticed this because I found all 0's in the newly added meta.data columns after `add_to_seurat()`. It appears that the indexing in `infercnv_obj@tumor_subclusters$subclusters[[clust]][[subclust]]` changes from a named vector with `analysis_mode='samples'` to a regular integer vector with `analysis_mode='subclusters'`. Thus, when run with subclusters, `names()` returns an empty vector here:
https://github.com/broadinstitute/infercnv/blob/master/R/seurat_interaction.R#L233

With `analysis_mode='samples'`:
```
infercnv::run(x, cutoff=0.1
                       out_dir=my_out_dir
                       cluster_by_groups=F,
                       denoise=T,
                       HMM=T)
```

```
> infercnv_obj = readRDS('run.final.infercnv_obj')
> for (clust in names(infercnv_obj@tumor_subclusters$subclusters)) {
+     for (subclust in names(infercnv_obj@tumor_subclusters$subclusters[[clust]])) {
+         print(length(names(infercnv_obj@tumor_subclusters$subclusters[[clust]][[subclust]])))
+     }
+ }
[1] 130
[1] 10
[1] 30
```

With `analysis_mode='subclusters'`:
```
infercnv::run(x, cutoff=0.1
                       out_dir=my_out_dir
                       cluster_by_groups=F,
                       denoise=T,
                       HMM=T,
                       analysis_mode='subclusters')
```

```
> infercnv_obj = readRDS('run.final.infercnv_obj')
> for (clust in names(infercnv_obj@tumor_subclusters$subclusters)) {
+     for (subclust in names(infercnv_obj@tumor_subclusters$subclusters[[clust]])) {
+         print(length(names(infercnv_obj@tumor_subclusters$subclusters[[clust]][[subclust]])))
+     }
+ }
[1] 0
[1] 0
[1] 0
[1] 0
```

**Comment by GeorgescuC** [comment] 2021-09-14 15:49
Hi @blakecaldwell ,

Thank you for reporting the issue! This is something that got introduced with the new default subclustering method that uses Leiden clustering. Your workaround works properly as the index information stored in the @tumor_subclusters field is correct. However compared to the other subclustering methods, the results are missing the names of the cells they match to which can be useful to others, so I went to the subclustering methods and made sure that information is now also propagated and simplified the code a bit.

For future runs, the issue is now fixed on the master branch. https://github.com/broadinstitute/infercnv/commit/4c8251956796818df3d1da9921d8d74ca6fc66e9

Regards,
Christophe.

**Closed** 2022-03-04 18:20 UTC
