### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by Sa753** [broadinstitute/infercnv#361] opened 2021-09-09 07:31 UTC
Dear team,

I have 2 problems with running infercnv::run() function. 

1-first, it takes incredible amount of time and memory. It has been running fo rover 17h and never finished for 22K cells. I am always stuck at step 18. I am running this without 'subclusters' which I don't like. The problem is even worse if I choose 'subclusters' as analysis_mode. I couldn't get beyond step 15 after 20h of running for 2500 cells. I am using 10 threads 
2-Second, Is it possible to discriminate which are malignant and which are not from this graph also, why is the graph incomplete as regards to chromosome bar?(please see image)

Thanks

![image](https://user-images.githubusercontent.com/53982843/132642368-97b1bfc3-6267-405f-b720-4c8cc2147ebc.png)

**Comment by GeorgescuC** [comment] 2021-09-14 15:46
Hi @Sa753 ,

1) For the subcluster option, if you use one of the latest versions of infercnv (1.7.2+), the run time has been drastically reduced when using the new method (now default too) that uses Leiden clustering, so you should give it a try if you want HMM predictions. In the results you posted, there are clearly different subclones within multiple groups, but in the current state, a single set of predictions is given per group, so it is impossible to have accurate predictions for whole groups without subdividing the cell populations. At the very least you should use one of pheight/qnorm/qgamma if you find the Leiden subclustering still too slow.
Step 18 is the bayesian network processing, and I expect groups that are bigger and non clonal to take longer to process, so splitting them should help speed there too.

2) For the chromosome bars, I have not encountered this issue before. Could you try running the plotting function again on the preliminary object to see if the error is reproducible? And if it is, can you try on a different machine? If it still does, I would need the object to debug the issue.
There a couple cells at the top and middle of your references that show some more left over signal, so I would double check quality and cell type labeling to see if the signal is true first.
For discriminating the cells within a group, you can:
-use the NGCHM interactive viewer (I see you have posted an issue about it, so once that is figured out)
-use the plot_per_group method to generate one plot per group, making things less compressed (you can also take advantage of the dynamic_resize option for taller heatmaps). I pushed a new commit that adds the option k_obs_group to it, allowing you to subdivide each group into the desired number. You can then look at the files generated with each plot to have the list of cells part of each subdivision.

Regards,
Christophe.

**Comment by andynkili** [comment] 2021-12-13 15:53
Any Update on the chromosome bar issue?
I have the same problem: having run inferCNV on a couple of different datasets and always ends up with incomplete chromosome bar plotted.

**Comment by Sa753** [comment] 2021-12-13 15:58
Hi ,

No I haven't heard again . I tried running on different machines and also on HPC but all gives this incomplete bar. 
I get it correct if I run it for human but if I tried to do it for mouse , I get this incomplete bar?.
I thought it might be an issue with the annotation file but I don't know.
I couldn't fix it
Are you running it for human or mouse?. 
Thx

**Comment by andynkili** [comment] 2021-12-13 16:03
I am running it on Human datasets

**Comment by GeorgescuC** [comment] 2021-12-13 16:48
Hi @Sa753 @andynkili ,

Have either of you gotten this issue while using one of the docker images as well?

If yes, could you please send me an infercnv object that allows to reproduce this issue so I can explore it? My email is available in the DESCRIPTION file.

Best,
Christophe.

**Comment by Sa753** [comment] 2021-12-13 21:58
I didn't try the docker image but I tried it on different computers and even on HPC. all produce the same incomplete bar. Would you please send your email and I will share an object with you?

**Comment by andynkili** [comment] 2021-12-14 02:59
Neither did I try the docker image. Do you think using the docker image will solve the issue?

**Comment by Sa753** [comment] 2021-12-16 18:29
Hi Christophe,

Any update on this please?

Thanks
Samar

**Comment by GeorgescuC** [comment] 2022-01-18 23:36
Hi @andynkili @Sa753 ,

Using the Docker image should remove variables specific to your installations and systems to at least help identify where the issue can be coming from since I am not able to reproduce it at this time.
One thing I do notice is that the missing color compared to normal are all from the 2nd half of the list, but are not all successive.

Does the issue happen with the example dataset included with infercnv as well?
If yes, could you please both run `sessionInfo()` and post the output here?

Regards,
Christophe.

**Comment by Sa753** [comment] 2022-05-01 08:01
Hi Chris,

I have emailed you the gene _order file and  data to reproduce the errors?. They also occurred when running  on the docker .
Thx

**Comment by GeorgescuC** [comment] 2022-05-04 00:31
Hi @Sa753 ,

I have received your email and will be taking a look to see if I can reproduce and fix the issue. Thank you!

Regards,
Christophe.

**Comment by GeorgescuC** [comment] 2022-05-18 20:53
For anyone that might encounter the issue, this has been fixed on the master branch on github and will be included in the next versions (1.12.1 and 1.13.1) when they are made. Thanks to @Sa753 for sharing their inputs so I could debug things.
The issue stemmed from small contigs in the position file that do not actually have expressed genes in them and are messing up the plot setup because they still exist as valid `levels` in the factor list in R, but are not counted when checking for `unique(contigs)`.

**Closed** 2022-06-30 15:55 UTC
