### ISSUE TITLE
STEP 18: Run Bayesian Network Model on HMM predicted CNV's ( assignment of an object of class “character” is not valid for @‘cnv_regions’ in an object of class “MCMC_inferCNV”; is(value, "factor") is not TRUE)

### ISSUE THREAD

**Issue by khl0798** [broadinstitute/infercnv#368] opened 2021-10-13 07:27 UTC
I reported an error at step 18， Who can help me look at the wrong reason for this question？？many thanks

![1634109807(1)](https://user-images.githubusercontent.com/7838505/137086196-006117d1-c7f0-4bd9-b1d7-7b55fb0ddce2.png)

data is as follows：

![1634109907(1)](https://user-images.githubusercontent.com/7838505/137086430-6f8bff5e-6fff-4ecb-9305-eec5782bd75f.png)

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.5 (Santiago)

Matrix products: default
BLAS/LAPACK: /.conda/envs/r403/lib/libopenblasp-r0.3.17.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] infercnv_1.3.3     SeuratObject_4.0.2 Seurat_4.0.4      

loaded via a namespace (and not attached):
  [1] plyr_1.8.6                  igraph_1.2.6               
  [3] lazyeval_0.2.2              splines_4.0.3              
  [5] listenv_0.8.0               scattermore_0.7            
  [7] GenomeInfoDb_1.26.7         ggplot2_3.3.5              
  [9] TH.data_1.1-0               digest_0.6.27              
 [11] foreach_1.5.1               htmltools_0.5.2            
 [13] HiddenMarkov_1.8-13         fansi_0.5.0                
 [15] magrittr_2.0.1              tensor_1.5                 
 [17] cluster_2.1.2               doParallel_1.0.16          
 [19] ROCR_1.0-11                 limma_3.46.0               
 [21] fastcluster_1.2.3           globals_0.14.0             
 [23] matrixStats_0.60.1          sandwich_3.0-1             
 [25] spatstat.sparse_2.0-0       colorspace_2.0-2           
 [27] ggrepel_0.9.1               dplyr_1.0.7                
 [29] crayon_1.4.1                RCurl_1.98-1.5             
 [31] jsonlite_1.7.2              libcoin_1.0-9              
 [33] spatstat.data_2.1-0         survival_3.2-13            
 [35] zoo_1.8-9                   iterators_1.0.13           
 [37] ape_5.5                     glue_1.4.2                 
 [39] polyclip_1.10-0             gtable_0.3.0               
 [41] zlibbioc_1.36.0             XVector_0.30.0             
 [43] leiden_0.3.9                DelayedArray_0.16.3        
 [45] future.apply_1.8.1          SingleCellExperiment_1.12.0
 [47] BiocGenerics_0.36.0         abind_1.4-5                
 [49] scales_1.1.1                futile.options_1.0.1       
 [51] mvtnorm_1.1-3               edgeR_3.32.1               
 [53] miniUI_0.1.1.1              Rcpp_1.0.7                 
 [55] viridisLite_0.4.0           xtable_1.8-4               
 [57] reticulate_1.20             spatstat.core_2.3-0        
 [59] stats4_4.0.3                htmlwidgets_1.5.4          
 [61] httr_1.4.2                  gplots_3.1.1               
 [63] RColorBrewer_1.1-2          ellipsis_0.3.2             
 [65] modeltools_0.2-23           ica_1.0-2                  
 [67] reshape_0.8.8               pkgconfig_2.0.3            
 [69] uwot_0.1.10                 deldir_0.2-10              
 [71] locfit_1.5-9.4              utf8_1.2.2                 
 [73] tidyselect_1.1.1            rlang_0.4.11               
 [75] reshape2_1.4.4              later_1.2.0                
 [77] munsell_0.5.0               tools_4.0.3                
 [79] generics_0.1.0              ggridges_0.5.3             
 [81] stringr_1.4.0               fastmap_1.1.0              
 [83] argparse_2.1.1              goftest_1.2-2              
 [85] fitdistrplus_1.1-3          caTools_1.18.2             
 [87] purrr_0.3.4                 RANN_2.6.1                 
 [89] coin_1.4-2                  pbapply_1.4-3              
 [91] future_1.22.1               nlme_3.1-153               
 [93] mime_0.11                   formatR_1.11               
 [95] rstudioapi_0.13             compiler_4.0.3             
 [97] plotly_4.9.4.1              png_0.1-7                  
 [99] spatstat.utils_2.2-0        tibble_3.1.4               
[101] stringi_1.7.4               futile.logger_1.4.3        
[103] lattice_0.20-44             Matrix_1.3-4               
[105] vctrs_0.3.8                 pillar_1.6.2               
[107] lifecycle_1.0.0             spatstat.geom_2.2-2        
[109] lmtest_0.9-38               RcppAnnoy_0.0.19           
[111] data.table_1.14.0           cowplot_1.1.1              
[113] bitops_1.0-7                irlba_2.3.3                
[115] httpuv_1.6.3                patchwork_1.1.1            
[117] GenomicRanges_1.42.0        R6_2.5.1                   
[119] promises_1.2.0.1            KernSmooth_2.23-20         
[121] gridExtra_2.3               rjags_4-11                 
[123] IRanges_2.24.1              parallelly_1.28.1          
[125] codetools_0.2-18            lambda.r_1.2.4             
[127] gtools_3.9.2                MASS_7.3-54                
[129] SummarizedExperiment_1.20.0 sctransform_0.3.2          
[131] multcomp_1.4-17             S4Vectors_0.28.1           
[133] GenomeInfoDbData_1.2.4      mgcv_1.8-36                
[135] parallel_4.0.3              grid_4.0.3                 
[137] rpart_4.1-15                tidyr_1.1.3                
[139] coda_0.19-4                 MatrixGenerics_1.2.1       
[141] Rtsne_0.15                  Biobase_2.50.0             
[143] shiny_1.6.0

**Comment by GeorgescuC** [comment] 2021-11-19 03:38
Hi @khl0798 ,

It seems you are using infercnv version 1.3.3, which is very outdated at this point. It's likely the issue is fixed in the current version of infercnv. After an update, you may want to delete the current output folder for the reload not to mistakenly reload the old object that will probably produce errors.

Regards,
Christophe.

**Closed** 2022-03-04 18:20 UTC

**Comment by RaghadShu** [comment] 2023-11-14 08:11
Hello @GeorgescuC, 
I am facing the same issue but it seems like version 1.3.3 is the latest version in the releases section https://github.com/broadinstitute/inferCNV/releases

Any ideas?

Best,
Raghad
