### ISSUE TITLE
Error in smooth.spline(x, mean_p0_table$p0) :    missing or infinite values in inputs are not allowed

### ISSUE THREAD

**Issue by Dimitri-Sid** [broadinstitute/infercnv#234] opened 2020-05-15 17:46 UTC
Hi,

I am having issues running infercnv and I have checked and do not not have missing data:

**ERROR:**
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed

any(is.null(infer_obj@expr.data) | is.na(infer_obj@expr.data) | is.infinite(infer_obj@expr.data))
FALSE
any(is.null(infer_obj@count.data) | is.na(infer_obj@count.data) | is.infinite(infer_obj@count.data))
FALSE

Any help would be much appreciated. Thanks!
Dimitri

**Comment by GeorgescuC** [comment] 2020-05-28 18:06
Hi @Dimitri-Sid ,

What version of infercnv are you currently using?

Would you be able to share privately the data with me and the options you are using so I can take a look?

Regards,
Christophe.

**Comment by DirtyHarry80** [comment] 2020-06-06 15:25
Hi Mr. Georgescu,
I am having the same issue. Please find the data set in question in the GEO: GSE118390. 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118390
Infer CNV version 1.2.1.
Do let me know if anything else could help.
Andrei Turtoi (aka DirtyHarry)

**Comment by GeorgescuC** [comment] 2020-06-18 22:41
Hi @DirtyHarry80 ,

Which files from the dataset are you using exactly? I have tried using both the [`GSE118389_counts_rsem.txt`](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE118389) file from NCBI and the [`counts_original.txt`](https://github.com/Michorlab/tnbc_scrnaseq/blob/master/data/counts_original.txt) file from the github repository, and am unable to reproduce the issue. I also do not see cells annotated as NK_cells in [the annotation on the github](https://github.com/Michorlab/tnbc_scrnaseq/blob/master/data/cell_types_tab_S9.txt) linked at the end of the paper cited in the dataset.

As the current newest version is 1.4.0 on the main branch of Bioconductor, you can try updating your version of infercnv and see if that fixes the issues (runs with R 4.0).

Regards,
Christophe.

**Comment by AlexanderAivazidis** [comment] 2020-07-07 11:58
Hi,

I have the same problem. I am using infercnv_1.5.0. I also have:

any(is.null(infercnv_obj@expr.data) | is.na(infercnv_obj@expr.data) | is.infinite(infercnv_obj@expr.data))
FALSE
any(is.null(infercnv_obj@count.data) | is.na(infercnv_obj@count.data) | is.infinite(infercnv_obj@count.data))
FALSE

But then:

> infercnv_obj = run(infercnv_obj,
+                        cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
+                              out_dir="/home/jovyan/HB_ZIK/inferCNV",  # dir is auto-created for storing outputs
+                              cluster_by_groups=T,   # cluster
+                              denoise=T,
+                              HMM=T,
+      resume_mode = FALSE
+                              )
INFO [2020-07-07 11:52:56] ::process_data:Start
INFO [2020-07-07 11:52:56] 

        STEP 1: incoming data

INFO [2020-07-07 11:53:23] 

        STEP 02: Removing lowly expressed genes

INFO [2020-07-07 11:53:23] ::above_min_mean_expr_cutoff:Start
INFO [2020-07-07 11:53:24] Removing 15548 genes from matrix as below mean expr threshold: 0.1
INFO [2020-07-07 11:53:24] validating infercnv_obj
INFO [2020-07-07 11:53:24] There are 5179 genes and 9752 cells remaining in the expr matrix.
INFO [2020-07-07 11:53:27] no genes removed due to min cells/gene filter
INFO [2020-07-07 11:53:40] 

        STEP 03: normalization by sequencing depth

INFO [2020-07-07 11:53:40] normalizing counts matrix by depth
INFO [2020-07-07 11:53:43] Computed total sum normalization factor as median libsize: 1776.500000
INFO [2020-07-07 11:53:43] Adding h-spike
INFO [2020-07-07 11:53:43] -no normals defined, using all observation cells as proxy
INFO [2020-07-07 11:53:43] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed

Here are the datasets for reproducibility (reduced to just 100 cells from 12000, but the error is the same):

[glioblastoma_counts_10X_Patient42.txt](https://github.com/broadinstitute/infercnv/files/4884654/glioblastoma_counts_10X_Patient42.txt)
[sample_annotation_10X_Patient42.txt](https://github.com/broadinstitute/infercnv/files/4884657/sample_annotation_10X_Patient42.txt)

Best wishes,

Alexander

**Comment by AlexanderAivazidis** [comment] 2020-07-07 11:59
PS: This is how I create the object in the first place:

infercnv_obj = CreateInfercnvObject(raw_counts_matrix="glioblastoma_counts_10X_Patient42.txt", annotations_file="sample_annotation_10X_Patient42.txt", delim = "\t", gene_order_file = "gencode_v19_gene_pos.txt", ref_group_names = NULL)

**Comment by GeorgescuC** [comment] 2020-07-10 18:45
Hi @AlexanderAivazidis ,

I downloaded the files you attached and ran infercnv with the arguments you used, and the run completed for me.

Can you run `sessionInfo()` and send the output?

[log.txt](https://github.com/broadinstitute/infercnv/files/4898558/log.txt)

Regards,
Christophe

**Comment by AlexanderAivazidis** [comment] 2020-07-11 16:40
[sample_annotation_10X_Patient42.txt](https://github.com/broadinstitute/infercnv/files/4907185/sample_annotation_10X_Patient42.txt)
[glioblastoma_counts_10X_Patient42.txt](https://github.com/broadinstitute/infercnv/files/4907186/glioblastoma_counts_10X_Patient42.txt)

Ok sorry you are right, these files subset to just 100 cells did not produce an error. But the files I am attaching now (subset to 500 cells), do produce this same error:

> infercnv_obj = CreateInfercnvObject(raw_counts_matrix="glioblastoma_counts_10X_Patient42.txt", annotations_file="sample_annotation_10X_Patient42.txt", delim = "\t", gene_order_file = "gencode_v19_gene_pos.txt", ref_group_names = NULL)
INFO [2020-07-11 16:34:22] Parsing matrix: glioblastoma_counts_10X_Patient42.txt
INFO [2020-07-11 16:34:24] Parsing gene order file: gencode_v19_gene_pos.txt
INFO [2020-07-11 16:34:25] Parsing cell annotations file: sample_annotation_10X_Patient42.txt
INFO [2020-07-11 16:34:25] ::order_reduce:Start.
INFO [2020-07-11 16:34:25] .order_reduce(): expr and order match.
INFO [2020-07-11 16:34:25] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 21673,503 Total=359346 Min=0 Max=629.
INFO [2020-07-11 16:34:25] num genes removed taking into account provided gene ordering list: 946 = 4.36487795875052% removed.
INFO [2020-07-11 16:34:25] validating infercnv_obj
> infercnv_obj = run(infercnv_obj,
+                    cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
+                          out_dir="/home/jovyan/HB_ZIK/inferCNV",  # dir is auto-created for storing outputs
+                          cluster_by_groups=T,   # cluster
+                          denoise=T,
+                          HMM=T, resume_mode = FALSE)
INFO [2020-07-11 16:34:31] ::process_data:Start
INFO [2020-07-11 16:34:31] 

        STEP 1: incoming data

INFO [2020-07-11 16:34:32] 

        STEP 02: Removing lowly expressed genes

INFO [2020-07-11 16:34:32] ::above_min_mean_expr_cutoff:Start
INFO [2020-07-11 16:34:32] Removing 19361 genes from matrix as below mean expr threshold: 0.1
INFO [2020-07-11 16:34:32] validating infercnv_obj
INFO [2020-07-11 16:34:32] There are 1366 genes and 503 cells remaining in the expr matrix.
INFO [2020-07-11 16:34:32] no genes removed due to min cells/gene filter
INFO [2020-07-11 16:34:32] 

        STEP 03: normalization by sequencing depth

INFO [2020-07-11 16:34:32] normalizing counts matrix by depth
INFO [2020-07-11 16:34:32] Computed total sum normalization factor as median libsize: 398.000000
INFO [2020-07-11 16:34:32] Adding h-spike
INFO [2020-07-11 16:34:32] -no normals defined, using all observation cells as proxy
INFO [2020-07-11 16:34:32] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed
> dim(infercnv_obj@expr.data)[1] 20727   503
> any(is.null(infercnv_obj@expr.data) | is.na(infercnv_obj@expr.data) | is.infinite(infercnv_obj@expr.data))
[1] FALSE
> any(is.null(infercnv_obj@count.data) | is.na(infercnv_obj@count.data) | is.infinite(infercnv_obj@count.data))
[1] FALSE


And here is my sessionInfo:

> sessionInfo()
R Under development (unstable) (2020-01-28 r77738)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] infercnv_1.5.0      BiocManager_1.30.10

loaded via a namespace (and not attached):
 [1] Biobase_2.47.3              tidyr_1.0.2                
 [3] edgeR_3.29.1                jsonlite_1.6.1             
 [5] splines_4.0.0               foreach_1.4.8              
 [7] lsei_1.2-0                  gtools_3.8.1               
 [9] argparse_2.0.1              assertthat_0.2.1           
[11] stats4_4.0.0                HiddenMarkov_1.8-11        
[13] coin_1.3-1                  GenomeInfoDbData_1.2.2     
[15] globals_0.12.5              pillar_1.4.3               
[17] lattice_0.20-40             glue_1.3.1                 
[19] limma_3.43.5                digest_0.6.25              
[21] GenomicRanges_1.39.2        RColorBrewer_1.1-2         
[23] XVector_0.27.1              colorspace_1.4-1           
[25] sandwich_2.5-1              plyr_1.8.6                 
[27] Matrix_1.2-18               pkgconfig_2.0.3            
[29] listenv_0.8.0               zlibbioc_1.33.1            
[31] purrr_0.3.3                 mvtnorm_1.1-0              
[33] scales_1.1.0                gdata_2.18.0               
[35] rjags_4-10                  BiocParallel_1.21.2        
[37] tibble_2.1.3                IRanges_2.21.5             
[39] ggplot2_3.3.0               TH.data_1.0-10             
[41] SummarizedExperiment_1.17.3 fastcluster_1.1.25         
[43] BiocGenerics_0.33.2         survival_3.1-11            
[45] magrittr_1.5                crayon_1.3.4               
[47] future_1.16.0               doParallel_1.0.15          
[49] nlme_3.1-145                MASS_7.3-51.5              
[51] gplots_3.0.3                tools_4.0.0                
[53] fitdistrplus_1.0-14         formatR_1.7                
[55] lifecycle_0.2.0             matrixStats_0.56.0         
[57] multcomp_1.4-12             S4Vectors_0.25.13          
[59] findpython_1.0.5            munsell_0.5.0              
[61] locfit_1.5-9.1              DelayedArray_0.13.7        
[63] lambda.r_1.2.4              compiler_4.0.0             
[65] GenomeInfoDb_1.23.13        caTools_1.18.0             
[67] rlang_0.4.5                 futile.logger_1.4.3        
[69] grid_4.0.0                  RCurl_1.98-1.1             
[71] iterators_1.0.12            SingleCellExperiment_1.9.2 
[73] bitops_1.0-6                npsurv_0.4-0               
[75] gtable_0.3.0                codetools_0.2-16           
[77] reshape_0.8.8               R6_2.4.1                   
[79] gridExtra_2.3               zoo_1.8-7                  
[81] dplyr_0.8.5                 libcoin_1.0-5              
[83] futile.options_1.0.1        KernSmooth_2.23-16         
[85] ape_5.3                     modeltools_0.2-23          
[87] parallel_4.0.0              Rcpp_1.0.3                 
[89] vctrs_0.2.3                 tidyselect_1.0.0           
[91] coda_0.19-3

**Comment by yangrunwei20** [comment] 2020-07-13 11:40
Hi! I have the same problem. I used the infercnv 1.4.0.

Here are the code and error report.
##
infercnv_obj = infercnv::run(infercnv_obj,
                              cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                              out_dir="~/CNV", 
                              cluster_by_groups=F,
                              denoise=T,
                              HMM=T)
INFO [2020-07-13 18:31:11] ::process_data:Start
INFO [2020-07-13 18:31:11] Checking for saved results.
INFO [2020-07-13 18:31:11] Trying to reload from step 2
INFO [2020-07-13 18:31:12] Trying to reload from step 1
INFO [2020-07-13 18:31:14] 

	STEP 1: incoming data

INFO [2020-07-13 18:31:19] 

	STEP 02: Removing lowly expressed genes

INFO [2020-07-13 18:31:19] ::above_min_mean_expr_cutoff:Start
INFO [2020-07-13 18:31:20] Removing 14783 genes from matrix as below mean expr threshold: 0.1
INFO [2020-07-13 18:31:20] validating infercnv_obj
INFO [2020-07-13 18:31:20] There are 634 genes and 13949 cells remaining in the expr matrix.
INFO [2020-07-13 18:31:20] no genes removed due to min cells/gene filter
INFO [2020-07-13 18:31:22] 

	STEP 03: normalization by sequencing depth

INFO [2020-07-13 18:31:22] normalizing counts matrix by depth
INFO [2020-07-13 18:31:23] Computed total sum normalization factor as median libsize: 0.000000
INFO [2020-07-13 18:31:23] Adding h-spike
INFO [2020-07-13 18:31:23] -hspike modeling of Normal cell
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed
##

Any help would be much appreciated! Many thanks!

Best wishes,
Runwei Yang

**Comment by aysouid** [comment] 2020-07-15 16:52
While we don't have zeros/NAs/infinities at run [check with @AlexanderAivazidis code], some genes are filtered out based on their expression in the reference set (based on the `cutoff` parameter in `infercnv::run` [https://rdrr.io/github/broadinstitute/inferCNV/man/run.html]). After removing these genes, then there are cells with zero total reads.

You could: (1) change `cutoff` (2) filter the cells to those with more than some lower-bound total read count (3) add more cells to the reference set to (hopefully) not trigger as many lost genes

**Comment by GeorgescuC** [comment] 2020-07-20 14:24
Hi @AlexanderAivazidis ,

In the case of your data, there was a double issue that should now be addressed in the master branch, if you can try updating your version of infercnv [as described on the wiki](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools).

For a detail of what was happening, the issue was that some of the cells only had reads mapping to MT genes, which are by default filtered out (`chr_exclude=c('chrX', 'chrY', 'chrM')`), so after removing them those cells had 0 reads. On top of that, the `min_max_counts_per_cell` filtering of cells was completely disabled by default, and was happening before removing chromosomes in `chr_exclude`. The `min_max_counts_per_cell` is now by default set to `c(100, +Inf)`, with a minimum of 1 read regardless of options used, and happens after applying `chr_exclude`.

As I do not have data for @Dimitri-Sid , @DirtyHarry80 or @aysouid , I do not know if the errors they have are due to the same issue, but I would recommend updating infercnv to the master branch [as described on the wiki](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools).

Regards,
Christophe.

**Comment by JJK-lab** [comment] 2020-10-10 12:31
me  too

**Comment by JJK-lab** [comment] 2020-10-15 08:05
I have solved the problem，this is my code.
dir.create("inferCNV/cell4")      
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, 
                             out_dir='inferCNV/cell4/', 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)
every time to run ,we  must change  create  new  file,Otherwise, the previous file will be automatically recognized by the system

**Comment by hiraksarkar** [comment] 2022-01-02 03:36
Hi, 

I am facing the same problem using  infercnv `‘1.8.1’`

**Closed** 2022-06-30 15:50 UTC

**Comment by mailmrcai** [comment] 2024-09-13 02:26
I solved this bug by filtering out the cluster classification named NA in annotations_file

**Comment by zunyun-Gong** [comment] 2024-09-18 15:40
I also met this bug. it is the mistake that you set the wrong cutoff. For example, you might use cutoff=1 for 10X scRNA-seq.
